version: '3.7'
services:
  mysql:
    container_name: myspend_mysql
    image: mysql:8.0.26
    restart: on-failure
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=centwong
    volumes:
      - myspend_mysql_volume::/var/lib/mysql
  redis:
    container_name: myspend_redis
    image: redis:7.2.3
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: on-failure

volumes:
  myspend_mysql_volume: