# =============================== SPRING CFG ===========================================
spring:
  flyway:
    url: jdbc:mysql://localhost:3306/artwork
    locations: classpath:/db/migration/artwork
    user: root
    password: centwong
  datasource:
    url: jdbc:mysql://localhost:3306/artwork
    username: root
    password: centwong
  jpa:
    show-sql: true

# =============================== JWT CFG ===========================================
jwt:
  secret: test-centwong-123-456-789-101112-131415-161718-192021_AZXCVBNM<>?

# =============================== ENDPOINT CFG ===========================================
management:
  endpoints:
    web:
      exposure:
        include: "*"